FROM oddbirds/pyjs:latest

# Headless Chrome for PDF generation:
ENV CHROME_BRANCH stable

RUN apt-get update -qqy \
    && apt-get install -qqy wget dumb-init gnupg ca-certificates apt-transport-https \
    && rm -rf /var/lib/apt/lists/* /var/cache/apt/*

RUN wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | apt-key add - \
    && echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list \
    && apt-get update -qqy \
    && apt-get install -qqy google-chrome-$CHROME_BRANCH \
    && rm /etc/apt/sources.list.d/google.list \
    && rm -rf /var/lib/apt/lists/* /var/cache/apt/*
