name: Build images

on:
  push:
    # branches:
    #   - 'master'
    # tags:
    #   - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - suffix: ''
            dockerfile: Dockerfile
          - suffix: -headless
            dockerfile: Dockerfile-headless
    steps:
      - uses: actions/checkout@v2
      - id: meta
        uses: docker/metadata-action@v3
        with:
          images: oddbirds/pyjs
      - uses: docker/setup-qemu-action@v1
      - id: buildx
        uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          file: ${{ matrix.dockerfile }}
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}${{ matrix.suffix }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=oddbirds/pyjs:buildcache${{ matrix.suffix }}
          cache-to: type=registry,ref=oddbirds/pyjs:buildcache${{ matrix.suffix }},mode=max
