name: Build images

on:
  push:
    # branches:
    #   - 'master'
    # tags:
    #   - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: meta
        uses: docker/metadata-action@v3
        with:
          images: oddbirds/pyjs
      - uses: docker/setup-qemu-action@v1
      - id: buildx
        uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: ${{ steps.buildx.outputs.platforms }}
