name: Build images

on:
  pull_request:
    branches:
      - master
  schedule:
    # Build everyday at 6:00 UTC
    - cron:  '0 6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        suffix: ['', '-headless']
        python: ['3.10', '3.9', '3.8']
        node: ['16', '14']
    steps:
      - uses: actions/checkout@v2
      - name: Set tag
        run: |
          echo "TAG=py${{ matrix.python }}-node${{ matrix.node }}${{ matrix.suffix }}" >> $GITHUB_ENV
      - id: meta
        uses: docker/metadata-action@v3
        with:
          images: oddbirds/pyjs
          tags: |
            type=raw,value=${{ env.TAG }}
      - uses: docker/setup-qemu-action@v1
      - id: buildx
        uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          file: Dockerfile${{ matrix.suffix }}
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=oddbirds/pyjs:buildcache-${{ env.TAG }}
          cache-to: type=registry,ref=oddbirds/pyjs:buildcache-${{ env.TAG }},mode=max
          build-args: |
            NODE_VERSION=${{ matrix.node }}
            PYTHON_VERSION=${{ matrix.python }}
